#!/usr/bin/env python3

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select, WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import io
import sys
import os
from collections import defaultdict
import time
import numpy as np

def get_credentials():
    with open('banner_credentials.txt','r') as f:
        contents = f.read()
    d = dict(l.split(':') for l in contents.strip().split('\n'))
    return d

def get_students():
    url = "https://banweb.pdx.edu"
    d = get_credentials()
    driver = webdriver.Firefox()
    time.sleep(2)
    driver.get(url)
    temp = WebDriverWait(driver, 20).until( \
        EC.presence_of_element_located((By.NAME, "j_username")))
    time.sleep(2)
    elem = driver.find_element_by_name("j_username")
    elem.clear()
    elem.send_keys(d['username'])
    elem = driver.find_element_by_name("j_password")
    elem.clear()
    elem.send_keys(d['password'])
    elem.send_keys(Keys.RETURN)
    elem = WebDriverWait(driver, 20).until( \
        EC.presence_of_element_located((By.LINK_TEXT, "Faculty Services")))
    time.sleep(2)
    elem.click()
    elem = WebDriverWait(driver, 20).until( \
        EC.presence_of_element_located((By.LINK_TEXT, "Summary Class List")))
    time.sleep(2)
    elem.click()
    elem = WebDriverWait(driver, 20).until( \
        EC.presence_of_element_located((By.NAME,'term')))
    select = Select(driver.find_element_by_name("term"))
    select.select_by_value(str(term))
    elem = WebDriverWait(driver, 20).until( \
        EC.presence_of_element_located((By.CSS_SELECTOR,'input[type="submit"]')))
    time.sleep(2)
    elem.click()

    # Select Course Form -- for now, assume that the correct course is selected by default.
    elem = WebDriverWait(driver, 20).until( \
        EC.presence_of_element_located((By.CSS_SELECTOR,'input[type="submit"]')))
    time.sleep(2)
    elem.click()

    # Table element we want
    elem = WebDriverWait(driver, 20).until( \
        EC.presence_of_element_located((By.CSS_SELECTOR,'table[summary*="list of students"]')))
    results = elem.get_attribute('outerHTML')

    with open('classlist.html','w') as f:
        f.write(results)

    driver.quit()

# Specify the term
# e.g. 201801 is Winter 2018
#      201802 is Spring 2018
#      201803 is Summer 2018
#      201804 is Fall 2018

term = 201803
get_students()
import roster_parser
os.remove('classlist.html')

